users:
  - username: "ansible-user"
  - username: "rmichau"
  - username: "pi"
    password: "$6$.aXmB946CCEheIEB$4ec70mhJ0Mz71qMlxU.NtFaSl50Hpaa/BBQSXXxP0PFOX47aL.df8Uqw/57N3AbHfvgOqaxGMceZmMhH/bAQo."
  - username: "github-worker" 
dns_ip: 192.168.1.68