---

- name: Install required packages
  apt:
    name:
      - gnupg2
      - curl
      - software-properties-common
      - ufw
    state: present


- name: Allow all access to tcp port allow
  community.general.ufw:
    rule: allow
    port: '3000'
    proto: tcp
  notify:
    - Start grafana
    - Enable grafana

- name: Install the grafana package
  apt:
    name: grafana
    state: present
    update_cache: yes
  notify:
    - Start grafana
    - Enable grafana