---

- name: init raspberry
  hosts: all
  gather_facts: yes
  become: true    
  roles:
    - name: common      
  tags:
    - common

- name: Install apache
  hosts: all
  become: true  
  roles:
    - name: apache
  tags:
    - apache


# - name: Install and init grafana
#   hosts: grafana
#   become: true  
#   roles:
#     - name: grafana
#   tags:
#     - grafana

- name: Install GitHub Actions Runner
  hosts: github_workers
  become: yes
  tags:
    - github-runner
  vars_files:
    - group_vars/github_worker/secrets.yml
    - group_vars/github_worker/vars.yml
  roles:
    - monolithprojects.github_actions_runner