---

- name: init raspberry
  hosts: all
  gather_facts: no
  become: true    
  roles:
    - name: common      

- name: init DNS server
  hosts: dns_server
  become: true  
  roles:
    - name: dnsmasq
  tags:
    - dns

- name: Install apache
  hosts: all
  become: true  
  roles:
    - name: apache
  tags:
    - apache
  
- name: Install Jenkins
  hosts: jenkins_server
  become: true  
  roles:
    - name: jenkins
  tags:
    - jenkins

- name: Install and init postgre
  hosts: postgres
  become: true  
  roles:
    - name: postgresql
  tags:
    - postgresql

- name: Install and init grafana
  hosts: grafana
  become: true  
  roles:
    - name: grafana
  tags:
    - grafana


- name: Install and init trilyzer
  hosts: trilyzer
  become: true  
  roles:
    - name: trilyzer
  tags:
    - trilyzer

- name: Install GitHub Actions Runner
  hosts: all
  become: yes
  tags:
    - github-runner
  vars_files:
    - group_vars/github_worker/secrets.yml
    - group_vars/github_worker/vars.yml
  roles:
    - monolithprojects.github_actions_runner