---

- name: init raspberry
  hosts: all
  gather_facts: no
  become: true    
  roles:
    - name: common      

- name: init DNS server
  hosts: dns_server
  become: true  
  roles:
    - name: dnsmasq
  tags:
    - dns

- name: Install apache
  hosts: all
  become: true  
  roles:
    - name: apache
  tags:
    - apache
  
- name: Install Jenkins
  hosts: jenkins_server
  become: true  
  roles:
    - name: jenkins
  tags:
    - jenkins

- name: Install and init postgre
  hosts: postgres
  become: true  
  roles:
    - name: postgresql
  tags:
    - postgresql