---

all:
  hosts: 
      pi1:
        ansible_ssh_host: 192.168.1.68
      pi2:
        ansible_ssh_host: 192.168.1.69
  children:
    dns_server:
      hosts:
        pi1:
    jenkins_server:
      hosts:
        pi1:
    postgres:
      hosts:
        pi1:
    grafana:
      hosts:
        pi1:
    trilyzer:
      hosts:
        pi1:
    github_workers:
      hosts:
        pi1:
  