---
- name: Update apt-get repo and cache
  apt: 
    update_cache: yes 
    force_apt_get: yes 
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt: 
    upgrade: dist 
    force_apt_get: yes

- name: Make sure we have vim installed
  apt:
    name: vim
    state: present

- name: Make sure we have git installed
  apt:
    name: vim
    state: present

- name: Make sure we vim git installed
  apt:
    name: vim
    state: present

